#!/usr/bin/env python3
"""Generate installer/languages/Uzbek.isl from Russian.isl template."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "installer" / "languages" / "Russian.base.isl"
OUT = ROOT / "installer" / "languages" / "Uzbek.isl"
RUSSIAN_URL = "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Russian.isl"

REPLACEMENTS: list[tuple[str, str]] = [
    ("LanguageName=Русский", "LanguageName=O'zbekcha"),
    ("LanguageID=$0419", "LanguageID=$0443"),
    ("Russian translation by Dmitry Kann, http://www.dk-soft.org/", "O'zbekcha translation for YVP Clipper"),
    ("SetupAppTitle=Установка", "SetupAppTitle=O'rnatish"),
    ("SetupWindowTitle=Установка — %1", "SetupWindowTitle=O'rnatish — %1"),
    ("UninstallAppTitle=Деинсталляция", "UninstallAppTitle=O'chirish"),
    ("UninstallAppFullTitle=Деинсталляция — %1", "UninstallAppFullTitle=O'chirish — %1"),
    ("InformationTitle=Информация", "InformationTitle=Ma'lumot"),
    ("ConfirmTitle=Подтверждение", "ConfirmTitle=Tasdiqlash"),
    ("ErrorTitle=Ошибка", "ErrorTitle=Xato"),
    (
        "SetupLdrStartupMessage=Данная программа установит %1 на ваш компьютер, продолжить?",
        "SetupLdrStartupMessage=Bu dastur %1 ni kompyuteringizga o'rnatadi. Davom etasizmi?",
    ),
    ("ButtonBack=< &Назад", "ButtonBack=< &Orqaga"),
    ("ButtonNext=&Далее >", "ButtonNext=&Keyingi >"),
    ("ButtonInstall=&Установить", "ButtonInstall=&O'rnatish"),
    ("ButtonCancel=Отмена", "ButtonCancel=Bekor qilish"),
    ("ButtonFinish=&Завершить", "ButtonFinish=&Tugatish"),
    ("ButtonYes=&Да", "ButtonYes=&Ha"),
    ("ButtonNo=&Нет", "ButtonNo=&Yo'q"),
    ("ButtonBrowse=&Обзор...", "ButtonBrowse=&Ko'rib chiqish..."),
    (
        "SelectLanguageTitle=Выберите язык установки",
        "SelectLanguageTitle=O'rnatish tilini tanlang",
    ),
    (
        "SelectLanguageLabel=Выберите язык, который будет использован в процессе установки.",
        "SelectLanguageLabel=O'rnatish jarayonida ishlatiladigan tilni tanlang.",
    ),
    ("WizardNext=Далее >", "WizardNext=Keyingi >"),
    ("WizardBack=< Назад", "WizardBack=< Orqaga"),
    ("WizardCancel=Отмена", "WizardCancel=Bekor qilish"),
    ("WizardFinish=Завершить", "WizardFinish=Tugatish"),
    ("WizardInstall=Установить", "WizardInstall=O'rnatish"),
    (
        "FinishedLabel=Программа %1 была успешно установлена на ваш компьютер.",
        "FinishedLabel=%1 dasturi kompyuteringizga muvaffaqiyatli o'rnatildi.",
    ),
    (
        "FinishedLabelNoIcons=Программа %1 была успешно установлена на ваш компьютер.",
        "FinishedLabelNoIcons=%1 dasturi kompyuteringizga muvaffaqiyatli o'rnatildi.",
    ),
    (
        "ClickFinish=Нажмите «Завершить», чтобы закрыть программу установки.",
        "ClickFinish=O'rnatish dasturini yopish uchun «Tugatish» ni bosing.",
    ),
    ("SetupTitle=", "SetupTitle="),
    ("ReadyLabel1=", "ReadyLabel1="),
]

# Broad phrase replacements for remaining Russian text
PHRASES: list[tuple[str, str]] = [
    ("Установка", "O'rnatish"),
    ("установки", "o'rnatish"),
    ("установку", "o'rnatish"),
    ("установлена", "o'rnatildi"),
    ("установлен", "o'rnatildi"),
    ("установить", "o'rnatish"),
    ("Установить", "O'rnatish"),
    ("Отмена", "Bekor qilish"),
    ("Далее", "Keyingi"),
    ("Назад", "Orqaga"),
    ("Завершить", "Tugatish"),
    ("Ошибка", "Xato"),
    ("программа", "dastur"),
    ("Программа", "Dastur"),
    ("компьютер", "kompyuter"),
    ("папку", "papka"),
    ("папка", "papka"),
    ("файл", "fayl"),
    ("Файл", "Fayl"),
    ("Да", "Ha"),
    ("Нет", "Yo'q"),
    ("OK", "OK"),
    ("Обзор", "Ko'rib chiqish"),
    ("Информация", "Ma'lumot"),
    ("Подтверждение", "Tasdiqlash"),
    ("версия", "versiya"),
    ("Версия", "Versiya"),
    ("продолжить", "davom etish"),
    ("Пожалуйста", "Iltimos"),
    ("выход", "chiqish"),
    ("Выйти", "Chiqish"),
    ("закрыть", "yopish"),
    ("Закрыть", "Yopish"),
    ("запущен", "ishga tushirilgan"),
    ("запуск", "ishga tushirish"),
    ("Запуск", "Ishga tushirish"),
    ("удалить", "o'chirish"),
    ("Удалить", "O'chirish"),
    ("создать", "yaratish"),
    ("Создать", "Yaratish"),
    ("выберите", "tanlang"),
    ("Выберите", "Tanlang"),
    ("язык", "til"),
    ("Язык", "Til"),
    ("диск", "disk"),
    ("Диск", "Disk"),
    ("каталог", "katalog"),
    ("Каталог", "Katalog"),
    ("временный", "vaqtinchalik"),
    ("Временный", "Vaqtinchalik"),
    ("невозможно", "mumkin emas"),
    ("Невозможно", "Mumkin emas"),
    ("не ", "emas "),
    ("нажмите", "bosing"),
    ("Нажмите", "Bosing"),
    ("чтобы", "uchun"),
    ("или", "yoki"),
    ("для ", "uchun "),
    ("Для ", "Uchun "),
    ("все", "barcha"),
    ("Все", "Barcha"),
    ("всех", "barcha"),
    ("пользователей", "foydalanuvchilar"),
    ("Пользователей", "Foydalanuvchilar"),
    ("администратора", "administrator"),
    ("Администратора", "Administrator"),
    ("Windows", "Windows"),
    ("прервана", "to'xtatildi"),
    ("завершена", "yakunlandi"),
    ("не завершена", "yakunlanmadi"),
    ("успешно", "muvaffaqiyatli"),
    ("Успешно", "Muvaffaqiyatli"),
    ("О программе", "Dastur haqida"),
    ("о программе", "dastur haqida"),
    ("Сайт", "Sayt"),
    ("сайт", "sayt"),
    ("папке", "papkada"),
    ("Папке", "Papkada"),
    ("файлы", "fayllar"),
    ("Файлы", "Fayllar"),
    ("повреждены", "buzilgan"),
    ("отсутствует", "yo'q"),
    ("Отсутствует", "Yo'q"),
    ("обнаружен", "topildi"),
    ("Обнаружен", "Topildi"),
    ("запущенный", "ishlayotgan"),
    ("экземпляр", "nusxa"),
    ("Экземпляр", "Nusxa"),
    ("приложения", "ilova"),
    ("Приложения", "Ilova"),
    ("приложение", "ilova"),
    ("Приложение", "Ilova"),
    ("продолжить?", "davom etasizmi?"),
    ("Продолжить?", "Davom etasizmi?"),
    ("выйти?", "chiqasizmi?"),
    ("Выйти?", "Chiqasizmi?"),
    ("готов", "tayyor"),
    ("Готов", "Tayyor"),
    ("готова", "tayyor"),
    ("Готова", "Tayyor"),
    ("готовы", "tayyor"),
    ("Готовы", "Tayyor"),
    ("выход из", "chiqish"),
    ("Выход из", "Chiqish"),
    ("режим", "rejim"),
    ("Режим", "Rejim"),
    ("только", "faqat"),
    ("Только", "Faqat"),
    ("меня", "men"),
    ("Меня", "Men"),
    ("вас", "siz"),
    ("Вас", "Siz"),
    ("ваш", "sizning"),
    ("Ваш", "Sizning"),
    ("вашего", "sizning"),
    ("вашем", "sizning"),
    ("ваши", "sizning"),
    ("этой", "bu"),
    ("Этой", "Bu"),
    ("этот", "bu"),
    ("Этот", "Bu"),
    ("эта", "bu"),
    ("Эта", "Bu"),
    ("эту", "bu"),
    ("Эту", "Bu"),
    ("эти", "bu"),
    ("Эти", "Bu"),
    ("данной", "ushbu"),
    ("Данной", "Ushbu"),
    ("данная", "ushbu"),
    ("Данная", "Ushbu"),
    ("данную", "ushbu"),
    ("Данную", "Ushbu"),
    ("будет", "bo'ladi"),
    ("Будет", "Bo'ladi"),
    ("будут", "bo'ladi"),
    ("Будут", "Bo'ladi"),
    ("может", "mumkin"),
    ("Может", "Mumkin"),
    ("можно", "mumkin"),
    ("Можно", "Mumkin"),
    ("нужно", "kerak"),
    ("Нужно", "Kerak"),
    ("требует", "talab qiladi"),
    ("Требует", "Talab qiladi"),
    ("требуются", "talab qilinadi"),
    ("Требуются", "Talab qilinadi"),
    ("поддерживает", "qo'llab-quvvatlaydi"),
    ("не поддерживает", "qo'llab-quvvatlamaydi"),
    ("версии", "versiyasi"),
    ("Версии", "Versiyasi"),
    ("версию", "versiyasi"),
    ("Версию", "Versiyasi"),
    ("более", "yanada"),
    ("Более", "Yanada"),
    ("позднюю", "yangiroq"),
    ("выше", "yuqori"),
    ("ниже", "past"),
    ("ранее", "avval"),
    ("позже", "keyinroq"),
    ("сейчас", "hozir"),
    ("Сейчас", "Hozir"),
    ("новую", "yangi"),
    ("новой", "yangi"),
    ("новая", "yangi"),
    ("копию", "nusxa"),
    ("Копию", "Nusxa"),
    ("проблему", "muammo"),
    ("Проблему", "Muammo"),
    ("проблема", "muammo"),
    ("Проблема", "Muammo"),
    ("устраните", "hal qiling"),
    ("Устраните", "Hal qiling"),
    ("получите", "oling"),
    ("Получите", "Oling"),
    ("запустив", "ishga tushirib"),
    ("запустите", "ishga tushiring"),
    ("Запустите", "Ishga tushiring"),
    ("закройте", "yoping"),
    ("Закройте", "Yoping"),
    ("открыть", "ochish"),
    ("Открыть", "Ochish"),
    ("выбрать", "tanlash"),
    ("Выбрать", "Tanlash"),
    ("выбран", "tanlangan"),
    ("Выбран", "Tanlangan"),
    ("выбрана", "tanlangan"),
    ("Выбрана", "Tanlangan"),
    ("выбрано", "tanlangan"),
    ("Выбрано", "Tanlangan"),
    ("путь", "yo'l"),
    ("Путь", "Yo'l"),
    ("пути", "yo'l"),
    ("Пути", "Yo'l"),
    ("место", "joy"),
    ("Место", "Joy"),
    ("места", "joy"),
    ("Места", "Joy"),
    ("диска", "disk"),
    ("Диска", "Disk"),
    ("свободного", "bo'sh"),
    ("Свободного", "Bo'sh"),
    ("свободно", "bo'sh"),
    ("место на", "joy"),
    ("недостаточно", "yetarli emas"),
    ("достаточно", "yetarli"),
    ("размер", "hajm"),
    ("Размер", "Hajm"),
    ("байт", "bayt"),
    ("Байт", "Bayt"),
    ("КБ", "KB"),
    ("МБ", "MB"),
    ("ГБ", "GB"),
    ("ТБ", "TB"),
    ("сек", "son"),
    ("мин", "daq"),
    ("ч", "soat"),
    ("д", "kun"),
    ("г", "yil"),
    (" из ", " dan "),
    ("Из ", "Dan "),
    (" в ", " ga "),
    ("В ", "Ga "),
    (" на ", " da "),
    ("На ", "Da "),
    (" с ", " bilan "),
    ("С ", "Bilan "),
    (" и ", " va "),
    ("И ", "Va "),
    (" но ", " lekin "),
    ("Но ", "Lekin "),
    (" если ", " agar "),
    ("Если ", "Agar "),
    (" когда ", " qachon "),
    ("Когда ", "Qachon "),
    (" что ", " nima "),
    ("Что ", "Nima "),
    (" как ", " qanday "),
    ("Как ", "Qanday "),
    (" где ", " qayerda "),
    ("Где ", "Qayerda "),
    (" к ", " ga "),
    ("К ", "Ga "),
    (" по ", " bo'yicha "),
    ("По ", "Bo'yicha "),
    (" без ", " siz "),
    ("Без ", "Siz "),
    (" через ", " orqali "),
    ("Через ", "Orqali "),
    (" после ", " keyin "),
    ("После ", "Keyin "),
    (" до ", " gacha "),
    ("До ", "Gacha "),
    (" уже ", " allaqachon "),
    ("Уже ", "Allaqachon "),
    (" ещё ", " yana "),
    ("Ещё ", "Yana "),
    (" также ", " shuningdek "),
    ("Также ", "Shuningdek "),
    (" рекомендуется", " tavsiya etiladi"),
    ("Рекомендуется", "Tavsiya etiladi"),
    ("все пользователи", "barcha foydalanuvchilar"),
    ("для всех", "barchasi uchun"),
    ("Для всех", "Barchasi uchun"),
    ("только для меня", "faqat men uchun"),
    ("Только для меня", "Faqat men uchun"),
    ("выход из программы установки", "o'rnatish dasturidan chiqish"),
    ("программы установки", "o'rnatish dasturi"),
    ("Программы установки", "O'rnatish dasturi"),
    ("программу установки", "o'rnatish dasturini"),
    ("Программу установки", "O'rnatish dasturini"),
    ("установочные файлы", "o'rnatish fayllari"),
    ("Установочные файлы", "O'rnatish fayllari"),
    ("установочная", "o'rnatish"),
    ("Установочная", "O'rnatish"),
    ("деинсталлятор", "o'chirish dasturi"),
    ("Деинсталлятор", "O'chirish dasturi"),
    ("деинсталляция", "o'chirish"),
    ("Деинсталляция", "O'chirish"),
    ("командная строка", "buyruq qatori"),
    ("параметр", "parametr"),
    ("Параметр", "Parametr"),
    ("недопустимый", "noto'g'ri"),
    ("Недопустимый", "Noto'g'ri"),
    ("уже запущена", "allaqachon ishga tushirilgan"),
    ("Уже запущена", "Allaqachon ishga tushirilgan"),
    ("не будет работать", "ishlamaydi"),
    ("не может быть установлена", "o'rnatib bo'lmaydi"),
    ("не может быть установлен", "o'rnatib bo'lmaydi"),
    ("выполнить вход", "tizimga kiring"),
    ("Выполнить вход", "Tizimga kiring"),
    ("систему как", "tizimga"),
    ("администратор", "administrator"),
    ("Администратор", "Administrator"),
    ("опытные пользователи", "kuchli foydalanuvchilar"),
    ("Power Users", "Power Users"),
    ("архитектур", "arxivlar"),
    ("процессоров", "protsessorlar"),
    ("Service Pack", "Service Pack"),
    ("требуется", "talab qilinadi"),
    ("Требуется", "Talab qilinadi"),
    ("требуют", "talab qiladi"),
    ("Требуют", "Talab qiladi"),
    ("обнаружил", "topdi"),
    ("Обнаружил", "Topdi"),
    ("чтобы продолжить", "davom etish uchun"),
    ("Чтобы продолжить", "Davom etish uchun"),
    ("чтобы выйти", "chiqish uchun"),
    ("чтобы закрыть", "yopish uchun"),
    ("чтобы завершить", "yakunlash uchun"),
    ("чтобы установить", "o'rnatish uchun"),
    ("чтобы удалить", "o'chirish uchun"),
    ("чтобы создать", "yaratish uchun"),
    ("чтобы запустить", "ishga tushirish uchun"),
    ("чтобы открыть", "ochish uchun"),
    ("чтобы выбрать", "tanlash uchun"),
    ("нажмите «OK»", "«OK» ni bosing"),
    ("нажмите «Отмена»", "«Bekor qilish» ni bosing"),
    ("«OK»", "«OK»"),
    ("«Отмена»", "«Bekor qilish»"),
    ("«Да»", "«Ha»"),
    ("«Нет»", "«Yo'q»"),
    ("«Завершить»", "«Tugatish»"),
    ("«Установить»", "«O'rnatish»"),
    ("«Далее»", "«Keyingi»"),
    ("«Назад»", "«Orqaga»"),
    ("«Обзор»", "«Ko'rib chiqish»"),
    ("«Создать папку»", "«Papka yaratish»"),
    ("«Да для всех»", "«Barchasi uchun ha»"),
    ("«Нет для всех»", "«Barchasi uchun yo'q»"),
    ("создать папку", "papka yaratish"),
    ("Создать папку", "Papka yaratish"),
    ("новая папка", "yangi papka"),
    ("Новая папка", "Yangi papka"),
    ("существующая", "mavjud"),
    ("Существующая", "Mavjud"),
    ("пустая", "bo'sh"),
    ("Пустая", "Bo'sh"),
    ("имя", "nom"),
    ("Имя", "Nom"),
    ("имени", "nom"),
    ("Имени", "Nom"),
    ("имя файла", "fayl nomi"),
    ("Имя файла", "Fayl nomi"),
    ("имя папки", "papka nomi"),
    ("Имя папки", "Papka nomi"),
    ("неверное", "noto'g'ri"),
    ("Неверное", "Noto'g'ri"),
    ("неверный", "noto'g'ri"),
    ("Неверный", "Noto'g'ri"),
    ("неверная", "noto'g'ri"),
    ("Неверная", "Noto'g'ri"),
    ("неверно", "noto'g'ri"),
    ("Неверно", "Noto'g'ri"),
    ("уже существует", "allaqachon mavjud"),
    ("Уже существует", "Allaqachon mavjud"),
    ("не существует", "mavjud emas"),
    ("Не существует", "Mavjud emas"),
    ("не найден", "topilmadi"),
    ("Не найден", "Topilmadi"),
    ("не найдена", "topilmadi"),
    ("Не найдена", "Topilmadi"),
    ("не найдено", "topilmadi"),
    ("Не найдено", "Topilmadi"),
    ("не удалось", "muvaffaqiyatsiz"),
    ("Не удалось", "Muvaffaqiyatsiz"),
    ("удалось", "muvaffaqiyatli"),
    ("Удалось", "Muvaffaqiyatli"),
    ("успешно установлена", "muvaffaqiyatli o'rnatildi"),
    ("успешно установлен", "muvaffaqiyatli o'rnatildi"),
    ("успешно удалена", "muvaffaqiyatli o'chirildi"),
    ("успешно удален", "muvaffaqiyatli o'chirildi"),
    ("была успешно", "muvaffaqiyatli"),
    ("Была успешно", "Muvaffaqiyatli"),
    ("был успешно", "muvaffaqiyatli"),
    ("Был успешно", "Muvaffaqiyatli"),
    ("были успешно", "muvaffaqiyatli"),
    ("Были успешно", "Muvaffaqiyatli"),
    ("закрыть программу установки", "o'rnatish dasturini yopish"),
    ("Закрыть программу установки", "O'rnatish dasturini yopish"),
    ("завершить установку", "o'rnatishni yakunlash"),
    ("Завершить установку", "O'rnatishni yakunlash"),
    ("завершить удаление", "o'chirishni yakunlash"),
    ("Завершить удаление", "O'chirishni yakunlash"),
    ("продолжить установку", "o'rnatishni davom ettirish"),
    ("Продолжить установку", "O'rnatishni davom ettirish"),
    ("продолжить удаление", "o'chirishni davom ettirish"),
    ("Продолжить удаление", "O'chirishni davom ettirish"),
    ("прервать установку", "o'rnatishni to'xtatish"),
    ("Прервать установку", "O'rnatishni to'xtatish"),
    ("прервать удаление", "o'chirishni to'xtatish"),
    ("Прервать удаление", "O'chirishni to'xtatish"),
    ("отменить установку", "o'rnatishni bekor qilish"),
    ("Отменить установку", "O'rnatishni bekor qilish"),
    ("отменить удаление", "o'chirishni bekor qilish"),
    ("Отменить удаление", "O'chirishni bekor qilish"),
    ("перезапустить", "qayta ishga tushirish"),
    ("Перезапустить", "Qayta ishga tushirish"),
    ("перезагрузить", "qayta yuklash"),
    ("Перезагрузить", "Qayta yuklash"),
    ("перезагрузка", "qayta yuklash"),
    ("Перезагрузка", "Qayta yuklash"),
    ("перезагрузите", "qayta yuklang"),
    ("Перезагрузите", "Qayta yuklang"),
    ("компьютер будет перезагружен", "kompyuter qayta yuklanadi"),
    ("Компьютер будет перезагружен", "Kompyuter qayta yuklanadi"),
    ("перезагрузить компьютер", "kompyuterni qayta yuklash"),
    ("Перезагрузить компьютер", "Kompyuterni qayta yuklash"),
    ("перезагрузить сейчас", "hozir qayta yuklash"),
    ("Перезагрузить сейчас", "Hozir qayta yuklash"),
    ("перезагрузить позже", "keyinroq qayta yuklash"),
    ("Перезагрузить позже", "Keyinroq qayta yuklash"),
    ("перезагрузить после", "keyin qayta yuklash"),
    ("Перезагрузить после", "Keyin qayta yuklash"),
    ("перезагрузить перед", "oldin qayta yuklash"),
    ("Перезагрузить перед", "Oldin qayta yuklash"),
    ("перезагрузить во время", "paytida qayta yuklash"),
    ("Перезагрузить во время", "Paytida qayta yuklash"),
    ("перезагрузить без", "siz qayta yuklash"),
    ("Перезагрузить без", "Siz qayta yuklash"),
    ("перезагрузить с", "bilan qayta yuklash"),
    ("Перезагрузить с", "Bilan qayta yuklash"),
    ("перезагрузить для", "uchun qayta yuklash"),
    ("Перезагрузить для", "Uchun qayta yuklash"),
    ("перезагрузить все", "barchasini qayta yuklash"),
    ("Перезагрузить все", "Barchasini qayta yuklash"),
    ("перезагрузить только", "faqat qayta yuklash"),
    ("Перезагрузить только", "Faqat qayta yuklash"),
]


def main() -> None:
    if not SRC.is_file():
        import urllib.request

        SRC.parent.mkdir(parents=True, exist_ok=True)
        urllib.request.urlretrieve(RUSSIAN_URL, SRC)
        print(f"Downloaded {SRC}")

    text = SRC.read_text(encoding="utf-8")
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    for old, new in PHRASES:
        text = text.replace(old, new)
    OUT.write_text(text, encoding="utf-8-sig")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
